* Conclusion
:PROPERTIES:
:CUSTOM_ID: sec:conclusion
:END:

This work presented a novel approach to the BEB charge scheduling problem. [[#sec:milp-pap]] introduced the concept of the
Berth Allocation Problem (BAP) which solves the problem of optimally assigning vessels to be serviced. From the BAP, the
Position Allocation Problem (PAP) was derived and introduced as the basis from which the work revolved. A Mixed Integer
Linear Program (MILP) was developed and from the PAP model that minimized the total charger count, energy consumption,
and was able to maintain a minimum State of Charge (SOC) throughout the working day. While MILP models maintain a level
of in the form of the objective function and constraints, certain limitations to mathematical modeling are made in order
to maintain linearity of the model. [[#sec:sa-pap]] introduced a Simulated Annealing implementation of the MILP PAP the same
considerations in the objective function while included an additional cost known as the demand cost.
[[#sec:nonlinear-battery-dynamics]] further introduces an implementation of non-linear battery dynamics that were
implemented in the SA PAP model.

[[#sec:milp-pap]] demonstrated an example of the MILP PAP formulation and compared its results to a heuristic-based
schedule, referred to as Qin-Modified. The MILP PAP optimization was run for \timeran seconds to a non-optimal solution.
The Qin-Modified and MILP schedule utilized a similar amount of fast chargers; however, the MILP schedule more readily
used the slow chargers to its advantage when the objective function saw fit. More importantly, the MILP PAP schedule
utilized approximately $0.1\cdot10^4$ kWh more than the Qin-Modified; however, the charges for the MILP schedule remained
above the constrained minimum SOC of \mincharge, and charged all the buses to \fpeval{\bcharge *100}% at the end of the
working day. The Qin-Modified schedule, on the other hand, allowed the SOC of certain BEBs to drop to 0%.

In [[#sec:sa-pap]] an example of the SA PAP algorithm was presented and compared against the MILP PAP and Qin-Modified
techniques. The SA PAP was run utilizing two different neighborhood searching techniques named the quick and heuristic
techniques, respectively. The quick SA's objective was to randomly search a wide neighborhood while the heuristic
technique was designed to incrementally search a neighborhood by randomly selecting a fast or slow charging queue and
then stepping through the queues one at a time. The quick and heuristic have comparable run times at
src_latex{\fpeval{\quicklocal * \tempcnt}} seconds and src_latex{\fpeval{\heuristiclocal * \tempcnt}} seconds,
respectively, but yielded vastly different results. The Qin-Modified utilized the fewest amount of chargers followed by
the MILP, heuristic SA, then the quick SA. The assignment cost applied to the objective function had no effect on the
results of the quick SA; however, the heuristic SA was more effective in minimizing the total chargers required.
Furthermore, the heuristic SA technique generated a solution approximating that of the MILP, but was unable to minimize
the charger count as efficiently. The quick SA utilized all the chargers available (i.e. was unable to minimize the
charger count).

Both of the SA techniques were unable to keep the SOC above the 25% SOC threshold with SOC falling to 6.34 kWh for the
heuristic SA and 29.8 kWh. The Qin-Modified had the SOC of three BEBs fall to 0% SOC. The schedule that consumed the
least amount of energy is the MILP PAP (4797.75 kW) with the heuristic SA coming in second (5785.76 kW). The difference
between the two being about src_latex{\fpeval{5785.76 - 4797.75}} kWh. The peak demands between the heuristic SA, quick
SA, and the MILP were very similar. The MILP had a peak demand of 1910 kW and the quick and heuristic SA had demand
peaks of 1911.9 kW. Overall, the most effective schedule was the MILP; however as SA has no guarantee of optimality, the
heuristic SA was able to generate a schedule that was "in the ballpark" of that of the MILP while further taking the
demand cost into consideration.

In [[#sec:nonlinear-battery-dynamics]], non-linear battery dynamics were derived and introduced in the SA PAP model. The
behavior of different convergence rates were demonstrated, and then an example was presented. Convergence rates of 0.1
and 0.002 were utilized for the fast and slow chargers, respectively. Overall, the non-linear SA performed better than
the heuristic technique except in terms of packing the schedule. This, however, is taken to be a factor of the SA
algorithm only being able to estimate optimality. Thus, as expected, the MILP produced the most optimal output of the
schedules. The non-linear SA was able to approximate the output relatively well while further taking peak demand into
consideration the non-linear battery dynamics model.

Further fields of interest are to investigate the performance of the quick and heuristic SA approaches utilizing a
denser set of routes to schedule as compared to the MILP. Non-linear dynamics would be of interest to incorporate into
the MILP model to further explore comparisons to the SA implementation. Another area of interest would be initializing a
MILP solver with a solution generated from an SA algorithm in an attempt to increase performance. Furthermore, an
interest in creating a robust strategy by accounting for uncertain arrival times by "fuzzifying" the arrival times. An
introduction into this method is provided in \ref{sec:fuzzy-sa-pap}.
