* INTRODUCTION
:PROPERTIES:
:CUSTOM_ID: sec:introduction
:END:

With an ever-increasing interest in the electrification of vehicles in the push for greener transportation, many
organizations and companies have been looking to adopt the electrification of fleet of vehicles [cite:@khan-2022-inves].
This transition is also stemming into the electrification of public bus transportation via battery power, i.e., battery
electric buses (BEBs) [cite:@li-2016-batter-elect;@guida-2017-zeeus-repor-europ]. In particular, agencies such as the
Utah Transit Authority (UTA), have directed focus in replacing their fleets with BEBs. Alongside all the benefits that
are associated with BEBs come new challenges that must be addressed prior to their integration into mainstream
utilization. The energy storage capacity of BEBs is typically significantly less than their combustion counterparts
while also have significantly longer refueling periods [cite:@xylia-2018-role-charg;@li-2016-batter-elect]. This is
further complicated due to the care that must be taken in prolonging the lifespan of the battery
[cite:@lutsey-2019-updat-elect;@edge-2021-lithium; @millner-2010-model-lithium]. As a further complication, BEB
refueling is no longer a fixed cost (i.e. price per gallon multiplied by tank size). Utility companies, in addition to
charging for the total energy consumed over a pay period, often further introduce a demand cost. The demand cost is
based on the peak power drawn during the pay period (i.e., charging multiple BEBs simultaneously), and can significantly
impact the overall monetary cost of maintaining the BEBs. Due to these factors, the charging schedules for the BEBs
significantly impacts the overall cost of utilizing the fleet. This work introduces a scheduling framework for a
fixed-schedule fleet of BEBs that utilizes a proportional battery dynamics model, accounts for multiple charger types,
allows partial charging, and attempts to minimize the monetary cost by considering the total energy consumed by the
schedule as well as peak power use.

BEBs have been in service for many major markets, North America, Europe, and China, for more than a decade with expected
growth in the near future [cite:@deng-2021-survey-elect]. The Asia Pacific market is forecasted to dominate the sales
and some major companies of the industry have also begun to enter the global market such as Volvo, BYD, and Proterra by
2025 [cite:@deng-2021-survey-elect]. Much focus has been placed on the engineering of individual BEBs such as battery
type, brake regenerative charging, optimal battery charging, and battery degradation [cite:@chen-2008-desig-grey;
@abdollahi-2016-optim-batter;@kuhne-2010-elect;@deng-2021-survey-elect]. The interest of route scheduling, charging
fleets, and optimizing the infrastructure are problems of more recent interest and are therefore timely and increasingly
relevant problems as EV/BEBs become more commonplace [cite:@hoke-2014-accoun-lithium; @sebastiani-2016-evaluat-elect;
@wei-2018-optim-spatio].

Works concerning charge planning often use a version of the vehicle scheduling problem [cite:@zhang-2021-optim-elect;
@duan-2021-refor-mixed; @rinaldi-2020-mixed-fleet; @tang-2019-robus-sched; @li-2014-trans-bus; @he-2020-optim-charg],
while others have based their implementation on alternative methods
[cite:@qarebagh-2019-optim-sched;@whitaker-2023-a-network]. [cite:@whitaker-2023-a-network] utilizes a network flow
approach to model the scheduling while [cite:@qarebagh-2019-optim-sched] utilizes what is known as the Position
Allocation Problem (PAP). Nearly all the literature reviewed considered consumption costs [cite:@jahic-2019-preem;
@frendo-2021-open-sourc; @qin-2016-numer-analy; @zhou-2020-bi-objec; @duan-2021-refor-mixed; @mortensen-2023-cost-minim;
@zhou-2020-collab-optim; @rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim], while fewer consider demand costs
[cite:@jahic-2019-preem; @frendo-2021-open-sourc; @qin-2016-numer-analy; @mortensen-2023-cost-minim;
@he-2020-optim-charg]. Many of these works introduce simplifying assumptions for the sake of computation. For example,
some approaches only consider fast chargers during planing [cite:@zhou-2020-collab-optim; @li-2014-trans-bus;
@wang-2017-optim-rechar; @sebastiani-2016-evaluat-elect; @wei-2018-optim-spatio]. Approaches that consider more than one
charger type typically isolate the specific charger types in different locations [cite:@tang-2019-robus-sched;
@he-2020-optim-charg].

Others have assumed that BEBs always charge to full capacity [cite:@duan-2021-refor-mixed; @zhang-2021-optim-elect;
@zhou-2020-bi-objec; @wang-2017-elect-vehic], partial charging utilizing a linear battery dynamics model
[cite:@wei-2018-optim-spatio; @he-2020-optim-charg; @mortensen-2023-cost-minim], or non-linear battery dynamics with
partial charging [cite:@whitaker-2023-a-network; @zhang-2021-optim-elect; @qin-2016-numer-analy; @jahic-2019-preem;
@frendo-2021-open-sourc]. Works that assumed scheduled BEBs always charge to full capacity significantly simplify the
scheduling problem, but eliminates the key factor in reducing the demand cost, partial charging
[cite:@tang-2019-robus-sched; @duan-2021-refor-mixed; @rinaldi-2020-mixed-fleet; @zhou-2020-collab-optim]. The
approaches that utilized non-linear charging profiles with partial charging achieve the same benefit in demand cost
reduction, with the added benefit of a higher fidelity at the expense of computation [cite:@zhang-2021-optim-elect].
Exceptions to this are [cite:@he-2020-optim-charg] that utilize a piecewise-linear charging profiles. This model has the
drawback of assuming that a charger is always available. [cite:@whitaker-2023-a-network] proposes a discrete linear
time-invariant dynamic model that results in an exponential decay non-linear charge profile.

The selected model for the battery charge dynamics, although pertinent to this work as it directly affects the quality
of the produced schedule, does not impact the considerations of battery health. Battery health begins to be of concern
when over-charging, under-charging, or forcing the battery to perform "deep" cycles [cite:@zhou-2020-bi-objec;
@millner-2010-model-lithium; @edge-2021-lithium]. Furthermore, other works have suggested that charging a battery nearly
to capacity is detrimental to the health and can significantly reduce the total charge cycles a battery may undergo
[cite:@edge-2021-lithium; @millner-2010-model-lithium]. While the charge profile for batteries are inherently
non-linear, some works have assumed proportional charging as linear battery dynamics remain a valid assumption when the
battery SOC is below 80% [cite:@liu-2020-batter-elect]. Thus, while linear dynamics may lack the fidelity of accuracy
above 80%, it is able to accurately estimate the SOC within a range that will guarantee battery health. Thus, this work
assumes that a linear model is sufficiently accurate to produce an operationally valid schedule while maintaining
battery health.

The work described in this thesis is similar to the work in [cite:@whitaker-2023-a-network]; however provides an
alternate method of modeling the problem in what is known as the Position Allocation Problem (PAP). The PAP is modeled
after the Berth Allocation Problem (BAP), which was designed to optimally schedule cargo vessels to be berthed and
serviced [cite:@buhrkal-2011-model-discr; @imai-2001-dynam-berth; @frojan-2015-contin-berth;]. The PAP utilizes this
notion to develop a model of assigning EVs to queue in ordered to be charged [cite:@qarebagh-2019-optim-sched].

Because of the PAP's modeling is similar to that of the BAP, literature from the BAP provides a foundation for the
development of the PAP in this work. The BAP has been studied in literature since the 1990s and provides a depth of work
to derive from [cite:@rodrigues-2022-berth]. The work to be introduced promises much potential for further research and
development in regard to scheduling BEBs. What follows is a Simulated Annealing (SA) implementation and extension of the
PAP utilizing Mixed Integer Linear Programming (MILP) constraints with non-linear battery dynamics.

In the next section, a review of relevant literature of BEBs is introduced and discussed. Background and a problem
statement will be elaborated further to provide context and a required basis of understanding prior to discussing the
objectives and approaches in [[#sec:objectives]] and [[#sec:approach]], respectively. The BEB queue scheduling problem discussed
throughout this section is of particular interest at this time in the BEB industry and requires more attention. The
research proposed directly approaches this problem by improving upon existing implementations to provide a robust and
accurate solution. In the subsequent sections the objectives will be introduced in [[#sec:objectives]] and the approach for
each objective will be discussed in [[#sec:approach]].

#+begin_comment
Public transportation systems are crucial in any urban area; however, the increased awareness and concern of
environmental impacts of petroleum based public transportation has driven an effort to reduce the pollutant footprint
[cite:@de-2014-simul-elect;@xylia-2018-role-charg;@guida-2017-zeeus-repor-europ;@li-2016-batter-elect]. Particularly,
the electrification of public bus transportation via battery power, i.e., battery electric buses (BEBs), has received
significant attention [cite:@li-2016-batter-elect]. Although the technology provides benefits beyond reduction in
emissions, such as lower driving costs, lower maintenance costs, and reduced vehicle noise, battery powered systems
introduce new challenges such as larger upfront costs, and potentially several hours long "refueling" periods
[cite:@xylia-2018-role-charg;@li-2016-batter-elect]. Furthermore, the problem is exacerbated by the constraints of the
transit schedule to which the fleet must adhere, the limited amount of chargers available, and the adverse affects in
the health of the battery due to fast charging [cite:@lutsey-2019-updat-elect].

BEBs have been in service for many major markets, North America, Europe, and China, for more than a decade with expected
growth in the near future [cite:@deng-2021-survey-elect]. The Asia Pacific market is forecasted to dominate the sales
and some major companies of the industry have also begun to enter the global market such as Volvo, BYD, and Proterra by
2025 [cite:@deng-2021-survey-elect]. Much focus has been placed on the engineering of individual BEBs such as battery
type, brake regenerative charging, optimal battery charging, and battery degradation [cite:@chen-2008-desig-grey;
@abdollahi-2016-optim-batter;@kuhne-2010-elect;@deng-2021-survey-elect]. The interest of route scheduling, charging
fleets, and optimizing the infrastructure are problems of more recent interest and are therefore timely and increasingly
relevant problems as EV/BEBs become more commonplace [cite:@hoke-2014-accoun-lithium; @sebastiani-2016-evaluat-elect;
@wei-2018-optim-spatio].

The literature shows an interest in solving the problem of assigning BEBs to charging queues or optimizing their
infrastructure [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;
@hoke-2014-accoun-lithium;@wang-2017-elect-vehic]. In fact, many works attempt to solve both problems simultaneously
barring some simplification whether it be only allowing chargers of a single type
[cite:@he-2020-optim-charg;@tang-2019-robus-sched]. If multiple chargers are used, then one of each type is assigned at
each location. Others have also assumed that a BEB shall recieve full charge upon each arrival
[cite:@wei-2018-optim-spatio;@wang-2017-elect-vehic;@zhou-2020-bi-objec;@wang-2017-optim-rechar]. Some works on the
stochastic effects of energy consumption while on route for a BEB as well as trip times [cite:@zhou-2020-collab-optim;
@bie-2021-optim-elect]. One other source, as far as the research for this work has shown, describes a method of
producing a BEB charge schedule wih a high fidelity while accounting for multiple charger times as well as being able to
minimize over the total charger count [cite:@whitaker-2023-a-network].

The work described in this thesis is similar to the work in [cite:@whitaker-2023-a-network]; however provides an
alternate method of modeling the problem in what is known as the Position Allocation Problem (PAP). The PAP is modeled
after the Berth Allocation Problem (BAP), which was designed to optimally schedule cargo vessels to be berthed and
serviced [cite:@buhrkal-2011-model-discr; @imai-2001-dynam-berth; @frojan-2015-contin-berth;]. The PAP utilizes this
notion to develop a model of assigning EVs to queue in ordered to be charged [cite:@qarebagh-2019-optim-sched].

Because of the PAP's extremely close modeling methods to the BAP, literature from the BAP can (and will) provide support
for the development of the PAP in this work. The BAP has been studied in literature since the 1990s and provides a depth
of work to derive from [cite:@rodrigues-2022-berth]. The work to be introduced promises much potential for further
research and development in regard to scheduling BEBs. What follows is a Simulated Annealing (SA)
implementation and extension of the PAP utilizing Mixed Integer Linear Programming (MILP) constraints with non-linear
battery dynamics.

In the next section, a review of relevant literature of BEBs is introduced and discussed. Background and a problem
statement will be elaborated further to provide context and a required basis of understanding prior to discussing the
objectives and approaches in [[#sec:objectives]] and [[#sec:approach]], respectively. The BEB queue scheduling problem discussed
throughout this section is of particular interest at this time in the BEB industry and requires more attention. The
research proposed directly approaches this problem by improving upon existing implementations to provide a robust and
accurate solution. In the subsequent sections the objectives will be introduced in [[#sec:objectives]] and the approach for
each objective will be discussed in [[#sec:approach]].
#+end_comment
