* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:introduction
:END:

The public transportation system is crucial in any urban area; however, the increased awareness and concern of
environmental impacts of petroleum based public transportation has driven an effort to reduce the pollutant footprint
[cite:@de-2014-simul-elect;@xylia-2018-role-charg;@guida-2017-zeeus-repor-europ;@li-2016-batter-elect]. Particularly,
the electrification of public bus transportation via battery power, i.e., battery electric buses (BEBs), has received
significant attention [cite:@li-2016-batter-elect]. Although the technology provides benefits beyond reduction in
emissions, such as lower driving costs, lower maintenance costs, and reduced vehicle noise, battery powered systems
introduce new challenges such as larger upfront costs, and potentially several hours long "refueling" periods
[cite:@xylia-2018-role-charg;@li-2016-batter-elect]. Furthermore, the problem is exacerbated by the constraints of the
transit schedule to which the fleet must adhere, the limited amount of chargers available, and the adverse affects in
the health of the battery due to fast charging [cite:@lutsey-2019-updat-elect].

Many recent efforts have been made to simultaneously solve the problems of route scheduling, and charging fleets and
determining the infrastructure upon which they rely, e.g., [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;
@hoke-2014-accoun-lithium;@wang-2017-elect-vehic]. Several simplifications are made to make these problems
computationally feasible. These simplifications to the charge scheduling model include utilizing only fast chargers
while planning [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;@wang-2017-optim-rechar;@zhou-2020-bi-objec;
@yang-2018-charg-sched;@wang-2017-elect-vehic;@qin-2016-numer-analy;@liu-2020-batter-elect]. If slow chargers are used,
they are only employed at the depot and not the station [cite:@he-2020-optim-charg;@tang-2019-robus-sched]. Some
approaches also simplify by assuming a full charge is always achieved
[cite:@wei-2018-optim-spatio;@wang-2017-elect-vehic;@zhou-2020-bi-objec;@wang-2017-optim-rechar]. Others have assumed
that the charge received is proportional to the time spent on the charger
[cite:@liu-2020-batter-elect;@yang-2018-charg-sched], which can be a valid assumption when the battery state-of-charge
(SOC) is below 80% charge [cite:@liu-2020-batter-elect].

The intent of the proposed work is to build upon the Position Allocation Problem [cite:@qarebagh-2019-optim-sched], a
modification of the well studied Berth Allocation Problem (BAP), as a means to schedule the charging of electric
vehicles [cite:@buhrkal-2011-model-discr;@frojan-2015-contin-berth;@imai-2001-dynam-berth]. The BAP model is a rectangle
packing problem with the goal of allocating space for incoming vessels to be berthed and serviced as depicted in
\autoref{subfig:bapexample}. The BAP can be modeled continuously and discretely both temporally and spatially
[cite:@buhrkal-2011-model-discr; @frojan-2015-contin-berth]. Furthermore, the demand to efficiently handle an
ever-growing demand for servicing cargo, with an estimated 1.24 billion of the 8.02 billion tonnes of all shipping cargo
in 2007 [cite:@buhrkal-2011-model-discr], implies a need for well planned berthing, which in turn provides a strong pool
of robust literature to draw from. Methods of handling multiple quays to handle general berthing scenarios
[cite:@frojan-2015-contin-berth;@dai-2008-suppl-chain-analy], heuristic procedures for quicker solve times have been
introduced [cite:@imai-2001-dynam-berth], static (full time horizon) and dynamic (rolling-time horizon) models have been
created for daily and real-time solutions, respectively, and even fuzzy set theory has been applied to allow for more
flexible schedules [cite:@bello-2019-fuzzy-activ]. An example of a standard BAP solution is visualized in [[img:baprep]].
The x and y-axis represent time and berthing space, respectively. The figure discretizes the berthing space, but it may
be continuous if desired. The shaded rectangles' widths represent their respective allocated service times, and their
heights represent the physical space taken by each vessel.

#+name: img:baprep
#+caption: Visual representation of a spatio-temporal solution plotted on an X-Y plane. The x-axis represnts time and the y-axis is the berthing space. The height of the shaded rectangles represent the space that a vessel occupies, and the width is the time consumed to service the vessel.
#+attr_latex: :width 0.6\textwidth
[[file:../sup-doc/milp-pap-paper-frontiers/img/baprep.pdf]]

Furthermore, this proposed work intends to extend the work of the PAP's novel approach to BEB charger scheduling even
further. The PAP's reenvisioning of the BAP provides the stepping stones on which to further extend the utility of this
robust technology. The intended work to be introduced, much of which has been completed, promises much potential for
further research and development in regard to BEBs. What follows is a proposal for a Simulated Annealing (SA)
implementation of the PAP utilizing Fully Fuzzy Mixed Integer Linear Programming (FFMILP) constraints with non-linear
battery dynamics.
