* INTRODUCTION
:PROPERTIES:
:CUSTOM_ID: sec:introduction
:END:

Public transportation system are crucial in any urban area; however, the increased awareness and concern of
environmental impacts of petroleum based public transportation has driven an effort to reduce the pollutant footprint
[cite:@de-2014-simul-elect;@xylia-2018-role-charg;@guida-2017-zeeus-repor-europ;@li-2016-batter-elect]. Particularly,
the electrification of public bus transportation via battery power, i.e., battery electric buses (BEBs), has received
significant attention [cite:@li-2016-batter-elect]. Although the technology provides benefits beyond reduction in
emissions, such as lower driving costs, lower maintenance costs, and reduced vehicle noise, battery powered systems
introduce new challenges such as larger upfront costs, and potentially several hours long "refueling" periods
[cite:@xylia-2018-role-charg;@li-2016-batter-elect]. Furthermore, the problem is exacerbated by the constraints of the
transit schedule to which the fleet must adhere, the limited amount of chargers available, and the adverse affects in
the health of the battery due to fast charging [cite:@lutsey-2019-updat-elect].

BEBs have been in service for many major markets, North America, Europe, and China, for more than a decade with expected
growth in the near future [cite:@deng-2021-survey-elect]. The Asia Pacific market is forecasted to dominate the sales
and some major companies of the industry have also began to enter the global market such as Volvo, BYD, and Proterra by
2025 [cite:@deng-2021-survey-elect]. Much focus has been placed on the engineering of individual BEBs such as battery
type, brake regenerative charging, optimal battery charging, and battery degradation [cite:@chen-2008-desig-grey;
@abdollahi-2016-optim-batter; @kühne-2010-elect;@deng-2021-survey-elect]. The interest of route scheduling, charging
fleets, and optimizing the infrastructure are problems of more recent interest and are therefore timely and increasingly
relevant problems as EV/BEBs become more commonplace [cite:@hoke-2014-accoun-lithium; @sebastiani-2016-evaluat-elect;
@wei-2018-optim-spatio].

The proposed work to be presented intends to develop a robust BEB charging model by extending the work of the Position
Allocation Problem's (PAP's) novel approach to scheduling Electric Vehicles (EVs). The PAP is modeled after the Berth
Allocation Problem (BAP), which was designed to optimally schedule cargo vessels to be berthed and serviced
[cite:@buhrkal-2011-model-discr; @imai-2001-dynam-berth; @frojan-2015-contin-berth;]. Because of the PAP's extremely
close modeling methods to the BAP, literature from the BAP can (and will) provide support for the development of the PAP
in this work. The BAP has been studied in literature since the 1990s and provides a depth of work to derive from
[cite:@rodrigues-2022-berth]. The proposed work also intends to introduce a sense of robustness by allowing uncertainty
in the arrival times of the BEBs. By "fuzzifying" the model, the "fuzzy" variables are allowed have upper and lower
bounds for which the model can provide solutions for. The work to be introduced promises much potential for further
research and development in regard to scheduling BEBs. What follows is a proposal for a Simulated Annealing (SA)
implementation and extension of the PAP utilizing Fully Fuzzy Mixed Integer Linear Programming (FFMILP) constraints with
non-linear battery dynamics.

In the next section, a review of relevant literature of BEBs is introduced and discussed. Background and a problem
statement will be elaborated further to provide context and a required basis of understanding prior to discussing the
objectives and approaches in [[#sec:objectives]] and [[#sec:approach]], respectively.

** Summary
:PROPERTIES:
:CUSTOM_ID: sec:intro-summary
:END:

The BEB queue scheduling problem discussed throughout this section is of particular interest at this time in the BEB
industry and requires more attention. The research proposed directly approaches this problem by improving upon existing
implementations to provide a robust and accurate solution. In the subsequent sections the objectives will be introduced
in [[#sec:objectives]] and the approach for each objective will be discussed in [[#sec:approach]].
