* INTRODUCTION
:PROPERTIES:
:CUSTOM_ID: sec:introduction
:END:

Public transportation system are crucial in any urban area; however, the increased awareness and concern of
environmental impacts of petroleum based public transportation has driven an effort to reduce the pollutant footprint
[cite:@de-2014-simul-elect;@xylia-2018-role-charg;@guida-2017-zeeus-repor-europ;@li-2016-batter-elect]. Particularly,
the electrification of public bus transportation via battery power, i.e., battery electric buses (BEBs), has received
significant attention [cite:@li-2016-batter-elect]. Although the technology provides benefits beyond reduction in
emissions, such as lower driving costs, lower maintenance costs, and reduced vehicle noise, battery powered systems
introduce new challenges such as larger upfront costs, and potentially several hours long "refueling" periods
[cite:@xylia-2018-role-charg;@li-2016-batter-elect]. Furthermore, the problem is exacerbated by the constraints of the
transit schedule to which the fleet must adhere, the limited amount of chargers available, and the adverse affects in
the health of the battery due to fast charging [cite:@lutsey-2019-updat-elect].

Many recent efforts have been made to simultaneously solve the problems of route scheduling, and charging fleets and
determining the infrastructure upon which they rely, e.g., [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;
@hoke-2014-accoun-lithium;@wang-2017-elect-vehic]. Several simplifications are made to make these problems
computationally feasible. These simplifications to the charge scheduling model include utilizing only fast chargers
while planning [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;@wang-2017-optim-rechar;@zhou-2020-bi-objec;
@yang-2018-charg-sched;@wang-2017-elect-vehic;@qin-2016-numer-analy;@liu-2020-batter-elect]. If slow chargers are used,
they are only employed at the depot and not the station [cite:@he-2020-optim-charg;@tang-2019-robus-sched]. Some
approaches also simplify by assuming a full charge is always achieved
[cite:@wei-2018-optim-spatio;@wang-2017-elect-vehic;@zhou-2020-bi-objec;@wang-2017-optim-rechar]. Others have assumed
that the charge received is proportional to the time spent on the charger
[cite:@liu-2020-batter-elect;@yang-2018-charg-sched], which can be a valid assumption when the battery state-of-charge
(SOC) is below 80% charge [cite:@liu-2020-batter-elect].

The proposed work presented here intends to extend the work of the PAP's novel approach to BEB charger scheduling even
further. The PAP's reenvisioning of the BAP provides the stepping stones on which to further extend the utility of this
robust technology. The intended work to be introduced, much of which has been completed, promises much potential for
further research and development in regard to BEBs. What follows is a proposal for a Simulated Annealing (SA)
implementation of the PAP utilizing Fully Fuzzy Mixed Integer Linear Programming (FFMILP) constraints with non-linear
battery dynamics.

** Background and Related Work
:PROPERTIES:
:CUSTOM_ID: sec:background-and-related-work
:END:

The charging problem is a problem that has been of increasing interest and therefore also increasing in relevancy in the
EV/BEB industry. It is thus important to address the state of the art by introducing relevant problems in BEB
scheduling. The areas of interest will then be detailed to the work proposed in this work, the Berth Allocation Problem
(BAP) and the Position Allocation Problem (PAP).

*** Problem Description
:PROPERTIES:
:CUSTOM_ID: sec:problem-description
:END:

#+include: "../sup-doc/sa-pap-paper/sections/problem-description.org" :only-contents t

*** State Of The Art
The intent of the proposed work is to build upon the Position Allocation Problem [cite:@qarebagh-2019-optim-sched], a
modification of the well studied Berth Allocation Problem (BAP), as a means to schedule the charging of electric
vehicles [cite:@buhrkal-2011-model-discr;@frojan-2015-contin-berth;@imai-2001-dynam-berth]. The BAP model is a rectangle
packing problem with the goal of allocating space for incoming vessels to be berthed and serviced as depicted in
\autoref{subfig:bapexample}. The BAP can be modeled continuously and discretely both temporally and spatially
[cite:@buhrkal-2011-model-discr; @frojan-2015-contin-berth]. Furthermore, the demand to efficiently handle an
ever-growing demand for servicing cargo, with an estimated 1.24 billion of the 8.02 billion tonnes of all shipping cargo
in 2007 [cite:@buhrkal-2011-model-discr], implies a need for well planned berthing, which in turn provides a strong pool
of robust literature to draw from. Methods of handling multiple quays to handle general berthing scenarios
[cite:@frojan-2015-contin-berth;@dai-2008-suppl-chain-analy], heuristic procedures for quicker solve times have been
introduced [cite:@imai-2001-dynam-berth], static (full time horizon) and dynamic (rolling-time horizon) models have been
created for daily and real-time solutions, respectively, and even fuzzy set theory has been applied to allow for more
flexible schedules [cite:@bello-2019-fuzzy-activ]. An example of a standard BAP solution is visualized in [[img:baprep]].
The x and y-axis represent time and berthing space, respectively. The figure discretizes the berthing space, but it may
be continuous if desired. The shaded rectangles' widths represent their respective allocated service times, and their
heights represent the physical space taken by each vessel.

#+name: img:baprep
#+caption: Visual representation of a spatio-temporal solution plotted on an X-Y plane. The x-axis represnts time and the y-axis is the berthing space. The height of the shaded rectangles represent the space that a vessel occupies, and the width is the time consumed to service the vessel.
#+attr_latex: :width 0.6\textwidth
[[file:../sup-doc/milp-pap-paper-frontiers/img/baprep.pdf]]

The PAP provides a basis for assigning BEBs to queues in order to be charged. Lets begin by defining some of the
assumptions made by the PAP. Each arriving vessel requires both time and space to be serviced and thus must be carefully
assigned a berthing location [cite:@imai-2001-dynam-berth]. Vessels are lined up parallel to the berth to be serviced
and are horizontally queued as shown in \autoref{subfig:bapexample}. The PAP utilizes this notion of queuing for
scheduling vehicles to be charged, as shown in \autoref{subfig:papexample}. The PAP is formulated as a rectangle packing
problem and assumes that vehicle charging will take a predefined amount of time, the quantity of vehicles that can
charge simultaneously is limited by the physical width of the vehicles and the charger length. It is assumed that each
vehicle visits the charger a single time [cite:@qarebagh-2019-optim-sched].

#+begin_src latex
\begin{subfigures}
    %%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    % BAP
    \begin{figure}[htpb]
    \centering
        \includestandalone{sup-doc/milp-pap-paper-frontiers/img/bap}
        \caption{Example of berth allocation. Vessels are docked in berth locations (horizontal) and are queued over
          time (vertical). The vertical arrow represents the movement direction of queued vessels and the horizontal
          arrow represents the direction of departure.}
        \label{subfig:bapexample}
    \end{figure}
    \hfill

    %%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    % PAP
    \begin{figure}[htpb]
    \centering
        \includestandalone{sup-doc/milp-pap-paper-frontiers/img/pap}
        \caption{Example of position allocation. Vehicles are placed in queues to be charged and move in the direction
          indicated by the arrow.}
        \label{subfig:papexample}
    \end{figure}
\end{subfigures}
#+end_src

As stated previously, the proposed project will further improve upon the PAP. While there are many avenues that may be
taken, the first task is to adapt the PAP to accommodate a BEB charging scenario where a fleet of buses is prescribed a
set of routes that they must adhere to. Firstly, due to the unknown charge state that a bus may arrive in, the charge
time must be variable, rather than an input parameter as is done currently for the BAP and PAP. Furthermore, both the
BAP and PAP consider each arrival to be unique; thus, a method of tracking buses must be implemented. As for queuing,
the PAP models the set of chargers as one continuous line; thus, the set of chargers must be discretized. The last set
of additions made upon the PAP is the design of the objective function. Input parameters are selected in such a manner
as to minimize the number of fast and slow charger utilized as well as minimize the energy consumption. The result is a
MILP formulation that coordinates charging times and charger type for every visit that each bus makes to the station
while considering a proportional dynamic charging model with scheduling constraints. The described improvements have
been completed as a proof of concept in what is known as the MILP-PAP. This proof of concept was written in the Python
programming language using Gurobi as the MILP solver.

While the linear battery dynamics is a valid assumption when the battery State-Of-Charge (SOC) is below 80%
[cite:@liu-2020-batter-elect], non-linear battery dynamics can be implemented to increase the accuracy of the model. A
common way to model the non-linear battery dynamics is utilizing CCCV [cite:@abdollahi-2016-optim-batter;
@chen-2008-desig-grey]. [cite:@zhang-2021-optim-elect] further suggests that the dynamics can be modeled as a piecewise
function containing a linear and non-linear component. Others have modeled the battery dynamics as a discrete first
order dynamics model [cite:@whitaker-2022-a-network]. The first-order differential system, when provided a step input,
approximates the non-linear relationship between time and the current SOC [cite:@whitaker-2022-a-network]. The
first-order differential method is method proposed to be pursued.

One of the drawbacks of the MILP implementation is the strict solution that is generated. Suppose that a solution was
generated, but due to weather conditions a bus arrives at the station five minutes late. The generated solution is no
longer valid due to one bus arriving late. This also could arise as an issue if a bus arrives early to the station. To
make matters worse, if a bus were to not adhere to the generated solution early on in the working day, the majority of
the solution is now void, and a new solution must be generated if optimality is desired. The crux of the problem is that
the time of arrival is uncertain. A potential solution to this problem is to fuzzify the MILP model.

Fuzzy mathematical programming is useful in situations where imprecise parameters exist [cite:@bello-2019-fuzzy-activ].
There are many methodologies that exist to solve Fully Fuzzy Linear Programs; however, the primary strategy of solving
FFLP problems is converting them into a classical (crisp) model
[cite:@bello-2019-fuzzy-activ;@nasseri-2013-fully;@kaur-2016-introd-fuzzy]. The chosen technique to pursue is the Kumar
and Kaurs method [cite:@kaur-2016-introd-fuzzy]. A model for the Fuzzy MILP-PAP has been drafted, but yet has been
implemented.

*** Mixed Integer Linear Programming
#+include: "../sup-doc/fuzzy-lp-paper/sections/preliminaries.org::*Mixed Integer Linear Program" :only-contents t

*** Overview of the BAP
:PROPERTIES:
:CUSTOM_ID: sec:overview-of-the-bap
:END:

#+include: "../sup-doc/milp-pap-paper-frontiers/sections/pap-problem.org::#sec:overview-of-bap" :only-contents t
