* INTRODUCTION
:PROPERTIES:
:CUSTOM_ID: sec:introduction
:END:

Public transportation system are crucial in any urban area; however, the increased awareness and concern of
environmental impacts of petroleum based public transportation has driven an effort to reduce the pollutant footprint
[cite:@de-2014-simul-elect;@xylia-2018-role-charg;@guida-2017-zeeus-repor-europ;@li-2016-batter-elect]. Particularly,
the electrification of public bus transportation via battery power, i.e., battery electric buses (BEBs), has received
significant attention [cite:@li-2016-batter-elect]. Although the technology provides benefits beyond reduction in
emissions, such as lower driving costs, lower maintenance costs, and reduced vehicle noise, battery powered systems
introduce new challenges such as larger upfront costs, and potentially several hours long "refueling" periods
[cite:@xylia-2018-role-charg;@li-2016-batter-elect]. Furthermore, the problem is exacerbated by the constraints of the
transit schedule to which the fleet must adhere, the limited amount of chargers available, and the adverse affects in
the health of the battery due to fast charging [cite:@lutsey-2019-updat-elect].

BEBs have been in service for many major markets, North America, Europe, and China, for more than a decade; however, the
Asia Pacific market is forecasted to dominate the sales [cite:@deng-2021-survey-elect]. Some major companies of the
industry have also began to enter the global market such as Volvo, BYD, and Proterra [cite:@deng-2021-survey-elect].
Much focus has been placed on the engineering of individual BEBs such as battery type, brake regenerative charging,
optimal battery charging, and battery degradation [cite:@chen-2008-desig-grey; @abdollahi-2016-optim-batter;
@kühne-2010-elect;@deng-2021-survey-elect]. The interest of route scheduling, charging fleets, and optimizing the
infrastructure are problems of more recent interest and are therefore timely and increasingly relevant problems as
EV/BEBs become more commonplace [cite:@hoke-2014-accoun-lithium; @sebastiani-2016-evaluat-elect;
@wei-2018-optim-spatio].

The proposed work to be presented intends to develop a robust BEB charging model by extending the work of the Position
Allocation Problem's (PAP's) novel approach to scheduling Electric Vehicles (EVs). The PAP is modeled after the Berth
Allocation Problem (BAP), which was designed to optimally schedule cargo vessels to be berthed and serviced
[cite:@buhrkal-2011-model-discr; @imai-2001-dynam-berth; @frojan-2015-contin-berth;]. Because of the PAP's extremely
close modeling methods to the BAP, literature from the BAP can (and will) provide support for the development of the PAP
in this work. The BAP has been studied in literature since the 1990s and provides a depth of work to derive from
[cite:@rodrigues-2022-berth]. The work to be introduced, much of which has been completed, promises much potential for
further research and development in regard to scheduling BEBs. What follows is a proposal for a Simulated Annealing (SA)
implementation of the PAP utilizing Fully Fuzzy Mixed Integer Linear Programming (FFMILP) constraints with non-linear
battery dynamics.

In the next section, a review of relevant literature of BEBs is introduced and discussed. Background and a problem
statement will be elaborated further to provide context and a required basis of understanding prior to discussing the
objectives and approaches in [[#sec:objectives]] and [[#sec:approach]], respectively.

** Background and Related Work
:PROPERTIES:
:CUSTOM_ID: sec:background-and-related-work
:END:

The BEB queue scheduling problem is one that has been of increasing interest and relevancy in the EV/BEB industry. It is
thus important to address the state of the art by introducing relevant problems in BEB queue scheduling, which will be
addressed first. A detailed problem description shall then be presented so the reader has a better understanding of the
proposition moving forward, and then miscellaneous introductory theory will be presented that.

*** State Of The Art
:PROPERTIES:
:CUSTOM_ID: sec:state-of-the-art
:END:

Many recent efforts have been made to simultaneously solve the problems of route scheduling, and charging fleets and
determining the infrastructure upon which they rely, e.g., [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;
@hoke-2014-accoun-lithium;@wang-2017-elect-vehic]. Several simplifications are made to make these problems
computationally feasible. These simplifications to the charge scheduling model include utilizing only fast chargers
while planning [cite:@wei-2018-optim-spatio;@sebastiani-2016-evaluat-elect;@wang-2017-optim-rechar;@zhou-2020-bi-objec;
@yang-2018-charg-sched;@wang-2017-elect-vehic;@qin-2016-numer-analy;@liu-2020-batter-elect]. If slow chargers are used,
they are only employed at the depot and not the station [cite:@he-2020-optim-charg;@tang-2019-robus-sched]. Some
approaches also simplify by assuming a full charge is always achieved
[cite:@wei-2018-optim-spatio;@wang-2017-elect-vehic;@zhou-2020-bi-objec;@wang-2017-optim-rechar].

In some works, it was assumed that the charge received is proportional to the time spent on the charger
[cite:@liu-2020-batter-elect;@yang-2018-charg-sched]. While the linear battery dynamics is a valid assumption when the
battery State-Of-Charge (SOC) is below 80% [cite:@liu-2020-batter-elect], non-linear battery dynamics can be implemented
more accurately model the charge curve. A common way to model the non-linear battery dynamics is utilizing Constant
Voltage (CV), Constant Current (CC), Constant Power (CP), and Constant Current Constant Power (CCCV)
[cite:@abdollahi-2016-optim-batter; @chen-2008-desig-grey]. It has also been suggested that the dynamics can be modeled
as a piecewise function containing a linear and non-linear component from which a piecewise function approach may be
taken for the CV and CC components [cite:@zhang-2021-optim-elect;@abdollahi-2016-optim-batter]. Others have modeled the
battery dynamics as a discrete first order dynamics model [cite:@whitaker-2022-a-network]. The first-order differential
system, when provided a step input, approximates the non-linear relationship between time and the current SOC
[cite:@whitaker-2022-a-network].

Works concerning charge planning primarily focused on a network flow approach
[cite:@whitaker-2022-a-network;@liu-2020-batter-elect]. The network flow approach provides an easy method of modeling
the scheduling by discretizing the time horizon to $n_Q$ sets of nodes. The nodes represent the chargers availability
and can have a maximum of one bus at a time. The buses can flow into a node to be charged and then later can exit
allowing a now bus to enter. The more difficult portion is modeling the interconnection between the discrete sets of
nodes such that flow between sets is consistent [cite:@whitaker-2022-a-network]. Another method that is more natural to
modeling the BEB charging scenario is the PAP [cite:@qarebagh-2019-optim-sched]. While the visits remain as discrete
events, the time that the BEB is on the charger is modeled in continuous time in a similar way as the BEB
[cite:@frojan-2015-contin-berth; @qarebagh-2019-optim-sched]. As described previously, the BAP literature may be used
for the PAP from the literature shows methods of handling multiple quays (sets of chargers) to handle general berthing
scenarios [cite:@frojan-2015-contin-berth;@dai-2008-suppl-chain-analy], heuristic procedures for quicker solve times
have been introduced [cite:@imai-2001-dynam-berth], static (full time horizon) and dynamic (rolling-time horizon) models
have been created for daily and real-time solutions, respectively, and even fuzzy set theory has been applied to allow
for more flexible schedules [cite:@bello-2019-fuzzy-activ].

An issue with the modeling introduced in the previous paragraph is the strict nature of the solutions produced. Fuzzy
mathematical programming is useful in situations where imprecise parameters exist [cite:@bello-2019-fuzzy-activ]. There
are many methodologies that exist to solve Fully Fuzzy Linear Programs, but the primary strategy of solving FFLP
problems is converting them into a classical (crisp) model
[cite:@bello-2019-fuzzy-activ;@nasseri-2013-fully;@kaur-2016-introd-fuzzy]. The BAP has been modeled utilizing Nasseri
Method in [cite:@bello-2019-fuzzy-activ]; however, to the extent of the research done for this work, FFLP has not been
applied to EV or BEB scheduling. Note that previous work has begun on the model for the Fuzzy MILP-PAP. The mathematics
have been drafted, but have yet been implemented.

*** Problem Description
:PROPERTIES:
:CUSTOM_ID: sec:problem-description
:END:

The intent of the proposed work is to build upon the Position Allocation Problem [cite:@qarebagh-2019-optim-sched], a
modification of the well studied Berth Allocation Problem (BAP), as a means to schedule the charging of electric
vehicles [cite:@buhrkal-2011-model-discr;@frojan-2015-contin-berth;@imai-2001-dynam-berth]. The PAP's goal is that of
allocating space for incoming BEBs to be queued and charged as depicted in \autoref{subfig:papexample}. The BEBs are
assumed to be on schedules that are defined in advance. That is, the times the BEBs are on their respective routes and
the time they are at the station are known. The BEBs' initial charges are assumed to be known, the discharges are
estimated by calculating an average bus speed, the time on route, and an average amount of energy consumed per mile, and
a specified final charge must be met for each BEB. An example of a standard PAP/BAP solution (their visual
representations are interchangeable) is visualized in \autoref{fig:bap}, note that the figure utilized BAP terminology.
The x and y-axis represent time and queuing space, respectively. The figure discretizes the queuing space, but it may be
continuous if desired as previously stated. The shaded rectangles' widths represent their respective allocated charge
times, and their heights represent the physical space taken by each EV.


#+begin_src latex
\begin{subfigures}
    %%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    % BAP
    \begin{figure}[htpb]
    \centering
        \includestandalone{sup-doc/milp-pap-paper-frontiers/img/bap}
        \caption{Example of berth allocation. Vessels are docked in berth locations (horizontal) and are queued over
          time (vertical). The vertical arrow represents the movement direction of queued vessels and the horizontal
          arrow represents the direction of departure.}
        \label{subfig:bapexample}
    \end{figure}
    \hfill

    %%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    % PAP
    \begin{figure}[htpb]
    \centering
        \includestandalone{sup-doc/milp-pap-paper-frontiers/img/pap}
        \caption{Example of position allocation. Vehicles are placed in queues to be charged and move in the direction
          indicated by the arrow.}
        \label{subfig:papexample}
    \end{figure}
\end{subfigures}
#+end_src


Now that the problem has been defined conceptually, the problem shall be defined in more mathematical terms.
#+include: "../sup-doc/sa-pap-paper/sections/problem-description.org::#sec:problem-description" :only-contents t

*** Mixed Integer Linear Programming

#+include: "../sup-doc/fuzzy-lp-paper/sections/preliminaries.org::*Mixed Integer Linear Program" :only-contents t

*** Overview of the BAP
:PROPERTIES:
:CUSTOM_ID: sec:overview-of-the-bap
:END:

#+begin_export latex
  \begin{figure}
    \centering
    \includegraphics{sup-doc/milp-pap-paper-frontiers/img/spatiotemporal-packing}
    \caption{Example of rectangle packing problem.}
    \label{fig:packexample}
  \end{figure}
#+end_export

#+include: "../sup-doc/milp-pap-paper-frontiers/sections/pap-problem.org::#sec:overview-of-bap" :only-contents t

*** Fuzzy Preliminaries
:PROPERTIES:
:CUSTOM_ID: sec:fuzzy-preliminaries
:END:

This section introduces the concept of fuzzy set theory by providing some basic definitions. The theory is then built on
to discuss Fully Fuzzy Linear Programming (FFLP). FFLP is a branch of Linear Programming where some of the parameters
are allowed to have uncertainty which will be further elaborated on. In this section a method of constructing FFLP is
introduced. Once the FFLP model has been introduced, a derivation of the Fuzzy BAP (FBAP) is introduced and
discussed.

**** Fuzzy Sets Theory
:PROPERTIES:
:CUSTOM_ID: sec:fuzzy-sets-theory
:END:

#+include: "../sup-doc/fuzzy-lp-paper/sections/preliminaries.org::*Fuzzy Sets Theory" :only-contents t

**** Fully Fuzzy Linear Programming
:PROPERTIES:
:CUSTOM_ID: sec:fully-fuzzy-linear-programming
:END:

#+include: "../sup-doc/fuzzy-lp-paper/sections/preliminaries.org::*Fully Fuzzy Linear Programming" :only-contents t

**** The Fuzzy BAP
:PROPERTIES:
:CUSTOM_ID: sec:the-fuzzy-bap
:END:

#+include: "../sup-doc/fuzzy-lp-paper/sections/the-fuzzy-bap.org::#sec:the-fuzzy-bap" :only-contents t

** Summary
:PROPERTIES:
:CUSTOM_ID: sec:intro-summary
:END:

The BEB queue scheduling problem discussed throughout this section is of particular interest at this time in the BEB
industry and requires more attention. The research proposed directly approaches this problem by improving upon existing
implementations to provide a robust and accurate solution. In the subsequent sections the objectives will be introduced
in [[#sec:objectives]] and the approach for each objective will be discussed in [[#sec:approach]].
