* MIXED INTEGER LINEAR PROGRAM WITH LINEAR BATTERY DYNAMICS
:PROPERTIES:
:CUSTOM_ID: sec:milp-pap
:END:

** Introduction
:PROPERTIES:
:custom_id: sec:milp-introduction
:END:

The contribution of this work is the extension of the PAP's novel approach to BEB charger scheduling. This incorporates
a proportional charging model into the MILP framework, includes consideration for multiple charger types, and
consideration of each route in the schedule. The last contribution is of importance because both the BAP and PAP
consider each arrival to be unique; thus, the tracking of battery charge from one visit to the next must be considered.
Furthermore, the input parameters for the model can be predefined in such a manner as to minimize the number of fast and
slow chargers utilized as well as minimize the energy consumption. That is, the model will simultaneously minimize the
number of chargers as well as the total consumed energy. The result is a MILP formulation that coordinates charging
times and charger type for every visit while considering a dynamic charge model with scheduling constraints.

The remainder of this chapter proceeds as follows: \autoref{sec:problemformulation} constructs the MILP for BEB
scheduling, including modifications to the PAP queuing constraints and the development of a dynamic charging model.
\autoref{sec:example} demonstrates an example of using the formulation to coordinate \A buses over \N total visits
to the station.

** Position Allocation Problem :noexport:
:PROPERTIES:
:custom_id: sec:the-position-allocation-problem
:END:
#+include: ../sup-doc/milp-pap-paper-frontiers/sections/pap-problem.org::#sec:the-position-allocation-problem :only-contents t

** A Rectangle Packing Formulation for BEB Charging
:PROPERTIES:
:custom_id: sec:problemformulation
:END:

#+include: ../sup-doc/milp-pap-paper-frontiers/sections/rectangle-packing.org::#sec:problemformulation :only-contents t

** Example
:PROPERTIES:
:custom_id: sec:example
:END:

#+include: ../sup-doc/milp-pap-paper-frontiers/sections/example.org::#sec:example :only-contents t
