* A SIMULATED ANNEALING APPROACH WITH NON-LINEAR BATTERY DYNAMICS
:PROPERTIES:
:CUSTOM_ID: sec:nonlinear-battery-dynamics
:END:

The models presented up to this point have employed linear battery dynamic constraints to estimate the SOC of the BEB
during its charging phase. While linear battery dynamics are accurate up to about an 80% SOC
[cite:@liu-2020-batter-elect], fidelity is lost after this point due to the non-linearity of the charge profile. This
chapter introduces a method of replacing the linear battery dynamics throughout this work with a non-linear dynamics
model. The non-linear model will be employed the SA algorithm derived in [[#sec:sa-pap]] The chapter proceeds as follows: an
introduction to the non-linear battery dynamics model is shown in [[#sec:nonlinear-model]] along with a proof and
description of how the model is incorporated. [[#sec:nonlinear-results]] presents and discusses the results.

** Non-linear Battery Dynamics Model
:PROPERTIES:
:CUSTOM_ID: sec:nonlinear-model
:END:

Modeling the charging dynamics is imperative to the model's accuracy as it is one of the main factors in terms of the
decision variables. If the SOC is improperly modeled, that will produce an erroneous depiction of the state of BEB
charges and could result in over or under charging. Thus, care must be taken into considering the BEB's charging model.
There are various methods of modeling the SOC of a battery and can vary in complexity based on the attempt to
incorporate temperature, battery degradation, and current
[cite:@zhang-2021-optim-elect;@chen-2008-desig-grey;@watrin-2012-multip-lithium].

Some of the conventional methods to charge batteries are: Constant Voltage (CV), Constant Current (CC), and Constant
Current Constant Voltage (CCCV) [cite:@arabsalmanabadi-2018-charg-techn]. In CCCV, a constant current is applied to a
battery until it reaches terminal voltage. At this point a constant voltage is applied as the charge current decreases
and the battery reaches full charge [cite:@chen-2008-desig-grey]. Thus, by extension, CV merely applies a constant
voltage and CC a constant current [cite:@arabsalmanabadi-2018-charg-techn].

As previously stated, the SOC can be accurately modeled until the battery reaches a charge of about 80%
[cite:@liu-2020-batter-elect]. At this point the SOC becomes non-linear. Naturally, it has been suggested by
[cite:@zhang-2021-optim-elect] that the SOC can be broken down into a linear and non-linear component. A plot of the SOC
for a battery is shown in [[fig:soc-plot]] to demonstrate these components [cite:@zhang-2021-optim-elect].

#+begin_src latex
  \begin{figure}

    \begin{minipage}{0.5\textwidth}
      \centering
      \includegraphics[width=0.9\textwidth]{img/soc-plot.png}
      \captionof{figure}{Illustration of non-linear charging profile.}
      \label{fig:soc-plot}
    \end{minipage}%
    \begin{minipage}{0.5\textwidth}
      \centering
      \includegraphics[width=0.9\textwidth]{img/nonlinear-bat.png}
      \captionof{figure}{Charging profiles for various convergence rates.}
      \label{fig:convergence-rates}
    \end{minipage}

  \end{figure}
#+end_src

While some leverage the linear and non-linear components to derive their SOC model [cite:@abdollahi-2016-optim-batter],
others have derived a first order equation to model this behavior [cite:@whitaker-2023-a-network]. Assume that a charge
will occur over $dt$ seconds. The SOC on the time step $h+1$ for bus $i$ can be determined by the simple discrete first
order equation

#+begin_export latex
\begin{equation}
  \eta_{\xi_i} = \bar{a}_q \eta_i - \bar{b}_q \kappa_{\Xi_i}\text{,}
\end{equation}
#+end_export

where

#+begin_export latex
\begin{equation}
\begin{array}{cc}
  \bar{a}_q = e^{a_q dt} & \bar{b}_q = e^{a_q dt} - 1\text{.}
\end{array}
\end{equation}
#+end_export

The equation is developed by using exact discretization [cite:@brogan-1990-moder-contr-theor], and is proved in
[cite:@whitaker-2023-a-network]. The lemma and proof are subsequently shown for completeness.

\begin{lemma}
Assume that the charge will occur over intervals over $\Delta$ seconds, the charge at time step $k+1$ for visit $i$ can be related to the charge at time step $k$ using charger $q$ as

\begin{equation}
\eta_{i,k+1} = \bar{a}_{q_i} \eta_{i,k} - \bar{b}_{q_i} M_i\text{,}
\end{equation}

where $\eta_{i, k}$ represents the SOC for bus $i$ at step $k$ and

\begin{equation}
\label{eq:nonlin-discrete-model}
\bar{a}_{q_i} = e^{a_{q_i} \Delta},\; \bar{b}_{q_i} = e^{a_{q_i} \Delta} - 1\text{.}
\end{equation}
\end{lemma}

\begin{proof}
A first-order, continuous model converging to $M_j$ at an exponential rate of $a_{q_i}$ can be expressed as

\begin{equation}
\label{eq:cont-exp}
\dot{s}_i = a_{q_i} \eta_i(t) - a_{q_i} M_i\text{.}
\end{equation}

The resulting discrete model in \ref{eq:nonlin-discrete-model} is obtained by using the exact discretation of an LTI system as is \cite{brogan-1990-moder-contr-theor}. Assuming $u(t)$ is held constant over the discrete step $\Delta$, the exact discretation of a general LTI system, represented as in $\dot{x}(t) = Ax(t) + Bu(t)$, is given by

\begin{equation}
\label{eq:exact-disc}
\begin{array}{ll}
x_{k+1} = \bar{A}x_k + \bar{B}u_k & \\
\bar{A} = e^{A\Delta} \\
\bar{B} = \int_0^\Delta e^{A-\tau} d\tau B\text{.}
\end{array}
\end{equation}

In \ref{eq:cont-exp}, both $a_{q_i}$ and $M_i$ are constants with no actual control input. To utilize this general discretization formula, \ref{eq:cont-exp} is rewritten as $\dot{s}_i = a_{q_i} \eta_i(t) - b_{q_i}u(t)$ where $b_{q_i} = a_{q_i}$ and $u(t) = -M_i$. Viewing this new equation in reference to \ref{eq:exact-disc}, the state $x(t)$ is replaced with $\eta_i(t)$ and the matrices, $A$ and $B$, are replaced with $a_{q_i}$ and $b_{q_i}$, respectively. Performing these substitutions the discretized forms of $a_{q_i}$ and $b_{q_i}$ become

\begin{equation}
\begin{array}{l}
\bar{a}_{q_i} = e^{a_{q_i} \Delta} \\
\bar{b}_{q_i} = a_{q_i} \int_0^\Delta e^{a_{q_i}(\Delta - \tau)} d\tau\text{.}
\end{array}
\end{equation}

The integral in $\bar{b}_{q_i}$ can be solved analytically by taking the antiderivative as

\begin{equation}
\bar{b}_{q_i} = a_{q_i} \Big( \left. -\frac{1}{a_{q_i}} e^{a_{q_i} (\Delta - \tau)} \right|_{\tau = 0}^{\tau = \Delta}\Big) = e^{a_{q_i}\Delta} - 1\text{.}
\end{equation}
\end{proof}

Thus, a visit may leverage this model by taking the initial SOC, $\eta_i$, substituting $\Delta$ for the charge duration, $s_i$,
and letting $q_i$ represent the convergence rate, the accumulated charge over visit $i$ can be directly calculated using
the exact discretization defined above. \ref{fig:convergence-rates} depicts the charge profile estimation utilizing
different convergence rates. Note from the figure, the values for the rate of convergence are negative.

** Results
:PROPERTIES:
:CUSTOM_ID: sec:nonlinear-results
:END:

The following results are generated utilizing the same parameters and problem setup as [[#sec:sa-pap-example]]. Convergence
rates of 0.1 and 0.002 are utilized for fast and slow chargers, respectively. As stated in
[cite:@whitaker-2023-a-network], a convergence rate of 0.1 leads a 90% charge of a 388 kWh battery in about 23 minutes
which is comparable to the 911 kW fast charger utilized in the slow model and a convergence rate of 0.01 leads to a 90%
charge in about four hours. Assuming linear battery dynamics, that leads to a slow charger of 87 kW. Thus, to match the
utilized 30 kW charger, a convergence rate of about 0.002 found to be comparable via plotting the convergence to 80% SOC
(i.e. the linear portion of the SOC charge profile). Furthermore, the heuristic technique was executed utilizing the
non-linear battery dynamics due to its better performance as discussed in the results of [[#sec:sa-pap-example]].

#+include: ../tab/nonlinear-charge-count.org

\ref{subfig:schedule-nonlinear-sa} depicts the charge schedule generated utilizing non-linear battery dynamics.
Similarly to before, the symbol represents the point at which a BEB begins charging. The horizontal line with vertical
tic indicate the time over which said BEB receives its charge. For the vertical axis of \ref{fig:nonlinear-schedule}
rows 0-14 represent the slow charging queues and rows 15-29 represent the fast charging queues. The schedule utilized a
total of eight slow charging queues, one of which is not utilized. The MILP and heuristic SA are included in
\ref{fig:nonlinear-schedule} as baseline comparisons against the presented non-linear SA. Note that the MILP and
heuristic schedules are generated utilizing linear battery dynamics.

\ref{tab:nonlinear-charge-count} tabulates the maximum and the required amount of charger queues for each schedule and
\ref{fig:charger-usage-nonlinear-sa} visually depicts the number of chargers utilized over the time horizon. Referring
to the slow charger values in \ref{tab:nonlinear-charge-count}, the MILP was the only technique able to present a
schedule that required no further packing of the schedule. The heuristic SA utilized at most nine chargers in seven
while requesting a total of nine queues. The non-linear schedule, on the other hand, was able to generate a schedule
that only utilized five charges in parallel, but requested eight total queues. Thus, as previously concluded, a method
of post-processing the schedule to further optimize the spacial component of the schedule could be of interest.

#+include: ../tab/nonlinear-charge.org

\ref{fig:nonlinear-sa-charge} plots the initial SOC of each visit over time horizon and \ref{tab:nonlinear-charge}
tabulates the mean and max demand SOC for each. The non-linear schedule maintained the highest mean SOC followed by the
heuristic, then the MILP. Although having the largest mean SOC, the non-linear SA was unable to keep the SOC of the BEBs
above the 25% threshold; however, the nonlinear schedule was more successful than the heuristic SA algorithm with a
minimum SOC of 57.84 kWh. Similarly to the results of the linear battery dynamics results of [[#sec:sa-pap]], a possible
method of assisting the SA in avoiding the BEBs going below the minimum threshold is to apply a safety factor, $S_{f}\nu_i
\kappa_i$ where $S_{f} > 1;\; S_f \in \mathbb{R}$.

#+include: ../tab/nonlinear-power.org

\ref{fig:power-usage-nonlinear-sa} plots the power usage over the time horizon and \ref{tab:nonlinear-power} tabulates
the mean and max demand for each. The non-linear SA was able to maintain a lower mean demand, as compared to that of the
heuristic SA, while the MILP PAP continues to maintain the lowest mean demand over all the schedules. In terms of peak
demand, there is not much difference between each schedule with a range of src_latex{\fpeval{1911.9 - 1910}} kW. The
demand of the non-linear SA contains longer sustained demand than the heuristic SA approach, which explains the larger
mean demand for tho non-linear SA as well as it surpassing the MILP in the total energy consumed at the end of the
working day.

The consumed energy by each schedule is shown in \ref{fig:energy-usage-nonlinear-sa}. The ordering of most energy
consumed to least is as follows: heuristic SA, non-linear SA, and the MILP PAP with the respective energy consumption
for each being 797.746 kWh, 4487.259 kWh, and 4256.746 kWh. The non-linear SA consumed about 231.1 kWh more than the
MILP PAP. Notably, the ordering of the schedule mean demands are consistent with the energy consumed.
