* OBJECTIVES
:PROPERTIES:
:CUSTOM_ID: sec:objectives
:END:

The field of BEB research provides exciting many avenues and is continuing to gain traction in industry as BEBs replace
their gasoline counterparts. This work will introduce a novel approach to BEB scheduling that minimizes monetary costs
for the user, provides a robust solution, and includes an accurate dynamic battery model. The PAP provides a solid
foundation from which this work derived. However, the PAP does not perfectly encapsulate the problem and thus needs some
modifications to accommodate the BEB model. The PAP does not account for the revisits of a BEB and therefore the
State-Of-Charge (SOC) cannot be tracked. The model does not account for multiple charger types, and in fact models the
charger as a single continuous bar. These accommodations must be accounted for and are included in the objectives for
the proposed BEB charging plan below.

- *Objective 1*: Mathematically model the PAP to optimally assign BEBs to queues with unknown charging times to allow consideration of consumption cost and battery health

  - *Task 1.1*: Modify PAP to enable multiple visits by a BEB with variable charger duration per visit.

  - *Task 1.2*: Incorporate heterogeneous charger capabilities into the PAP to model slow and fast charging, minimize
    and total charger count. Slow charging will be incentivized for battery health and consumption cost.

- *Objective 2*: Mathematically model non-linear battery dynamics to increase the accuracy of the SOC estimate

  - *Task 2.1*: Incorporate non-linear battery dynamics into the model
