* Proposed Project
:PROPERTIES:
:CUSTOM_ID: sec:proposed-project
:END:

The PAP provides a basis for assigning BEBs to queues in order to be charged. Each arriving vessel requires both time
and space to be serviced and thus must be carefully assigned a berthing location [cite:@imai-2001-dynam-berth]. Vessels
are lined up parallel to the berth to be serviced and are horizontally queued as shown in \autoref{subfig:bapexample}.
The PAP utilizes this notion of queuing for scheduling vehicles to be charged, as shown in \autoref{subfig:papexample}.
The PAP is formulated as a rectangle packing problem by assuming that vehicle charging will take a fixed amount of time,
the amount of vehicles that can charge is limited by the physical width of the vehicles, and each vehicle visits the
charger a single time [cite:@qarebagh-2019-optim-sched].

As stated previously, the proposed project will further improve upon the PAP. While there are many avenues that may be
taken, the primary focus is to adapt the PAP to accommodate a BEB charging scenario where a fleet of buses is prescribed
a set of routes that they must adhere to. Firstly, due to the unknown charge state that a bus will arrive in, the charge
time must be variable, rather than an input parameter as is done currently for the BAP and PAP. Furthermore, both the
BAP and PAP consider each arrival to be unique; thus, a method of tracking buses must be implemented. As for queuing,
the PAP models the set of chargers as one continuous line; thus, the set of chargers must be discretized. The last set
of additions made upon the PAP is the design of the objective function. Input parameters are selected in such a manner
as to minimize the number of fast and slow charger utilized as well as minimize the power consumption. The result is a
MILP formulation that coordinates charging times and charger type for every visit that each bus makes to the station
while considering a dynamic charge model and scheduling constraints. The described improvements have been completed as a
proof of concept in what is known as the MILP-PAP.

While the linear battery dynamics is a valid assumption when the battery State-Of-Charge (SOC) is below 80%
[cite:@liu-2020-batter-elect], nonlinear battery dynamics can be implemented to increase the accuracy of the model's
battery charging dynamics. A common way to model the non-linear battery dynamics is utilizing CCCV
[cite:@abdollahi-2016-optim-batter; @chen-2008-desig-grey]. [cite:@zhang-2021-optim-elect] further suggests that the
dynamics can be modeled as a piecewise function containing a linear and nonlinear components. Others have modeled the
battery dynamics as a discrete first order dynamics model [cite:@whitaker-2022-a-network]. The first-order differential
system, when provided a step input, approximates the non-linear relationship between time and the current SOC
[cite:@whitaker-2022-a-network]. The first-order differential method is method proposed to be pursued.

One of the drawbacks of the MILP implementation is the strict solution that is generated. Suppose that a solution was
generated, but due to weather conditions a bus arrives at the station five minutes late. The generated solution is no
longer valid due to one bus arriving late. This also could arise as an issue if a bus arrives early to the station. To
make matters worse, if a bus were to not adhere to the generated solution early on in the working day, the majority of
the solution is now void, and a new solution must be generated if optimality is desired. The crux of the problem is that
the time of arrival is uncertain. A potential solution to this problem is to fuzzify the MILP model.

Fuzzy mathematical programming is useful in situations where imprecise parameters exist [cite:@bello-2019-fuzzy-activ].
There are many methodologies that exist to solve Fully Fuzzy Linear Programs; however, the primary strategy of solving
FFLP problems is converting them into a classical (crisp) model
[cite:@bello-2019-fuzzy-activ;@nasseri-2013-fully;@kaur-2016-introd-fuzzy]. The chosen technique to pursue is the Kumar
and Kaurs method [cite:@kaur-2016-introd-fuzzy]. A model for the Fuzzy MILP-PAP has been drafted, but yet has been
implemented.

# --------------------------------------------------------------------------------
# BAP and PAP comparison
#+begin_src latex
\begin{subfigures}
    %%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    % BAP
    \begin{figure}[htpb]
    \centering
        \includestandalone{sup-doc/milp-pap-paper-frontiers/img/bap}
        \caption{Example of berth allocation. Vessels are docked in berth locations (horizontal) and are queued over
          time (vertical). The vertical arrow represents the movement direction of queued vessels and the horizontal
          arrow represents the direction of departure.}
        \label{subfig:bapexample}
    \end{figure}
    \hfill

    %%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    % PAP
    \begin{figure}[htpb]
    \centering
        \includestandalone{sup-doc/milp-pap-paper-frontiers/img/pap}
        \caption{Example of position allocation. Vehicles are placed in queues to be charged and move in the direction
          indicated by the arrow.}
        \label{subfig:papexample}
    \end{figure}
\end{subfigures}
#+end_src
