* A SIMULATED ANNEALING APPROACH WITH LINEAR BATTERY DYNAMICS
:PROPERTIES:
:CUSTOM_ID: sec:sa-pap
:END:

** Introduction
:PROPERTIES:
:CUSTOM_ID: sec:sa-introduction
:END:

This work aims to expand on the PAP by introducing a Simulated Annealing (SA) framework that utilizes linear battery
dynamics, accounts for partial charging, minimizes total charger count, allows for multiple charger types, minimizes
consumption cost, and minimizes demand cost. These contributions are demonstrated via simulation and comparison to two
other models: the Mixed Integer Linear Program (MILP) implementation of the PAP and what is known as the Qin-Modified
technique.

The remainder of this chapter goes as follows. [[#sec:sa-problem-description]] provides the problem statement associated
with this work. [[#sec:sa-optimization-problem]] provides a description of the input parameters and decision variables then
introduces the structure of the formulation. In [[#sec:sa-simulated-annealing]], the concept and theory of SA is introduced.
In particular, the algorithms and methods utilized for the SA implementation for this work are discussed.
[[#sec:sa-optimization-algorithm]] combines the previous sections to introduce the particular pseudocode for the SA PAP. In
[[#sec:sa-example]], an example problem is provided to demonstrate the capability of the work provided in this paper. The
results will be presented and discussed.

** Problem Description
:PROPERTIES:
:CUSTOM_ID: sec:problem-description
:END:

#+include: ../sup-doc/sa-pap-paper/sections/problem-description.org::#sec:sa-problem-description :only-contents t

** Optimization Problem
:PROPERTIES:
:CUSTOM_ID: sec:optimization-problem
:END:

#+include: ../tab/sa-vars.org
#+include: ../sup-doc/sa-pap-paper/sections/optimization-problem.org::#sec:sa-optimization-problem :only-contents t

** Simulated Annealing
:PROPERTIES:
:CUSTOM_ID: sec:simulated-annealing
:END:

#+include: ../sup-doc/sa-pap-paper/sections/simulated-annealing.org::#sec:sa-simulated-annealing :lines "5-20"

*** Cooling Equation
:PROPERTIES:
:CUSTOM_ID: cooling-equation-experimental
:END:

The temperature function models a "rate of cooling" for the SA process. Initially, when the temperature is high, SA
encourages exploration. As the process begins to "cools down" (in accordance to the cooling schedule), it begins to
encourage local exploitation of the solution (rather than exploration)
[cite:@rutenbar-1989-simul-anneal-algor;@henderson-1989-theor-pract]. There are three common basic types of cooling
equations: linear, geometric, and exponential. Each schedule type is depicted in \ref{fig:cool}
[cite:@keller-2019-multi-objec]. Every plot begins with an initial temperature of $T_0 = 500^\circ\; C$ and a final
temperature of $T_f = 1^\circ\; C$. The different cooling schedules dictate the rate at which the algorithm progressively
disallows exploration. Let the vector of temperatures described by a cooling schedule be defined as $t$. Furthermore,
let an element of the vector be denoted as $t_m \in t$, where $m \in [0,...,M]$ and $M = \lvert t \rvert$.

A linear cooling schedule is defined by $t_m = t_{m-1} - \beta_0$. The terms utilized in \ref{fig:cool} are $t_0 = \Tau_0$
and $\beta_0 = 1/2\; C^\circ$. An exponential cooling schedule is defined by the difference equation $t_m = e^{-\beta_2}t_{m-1}$.
The values utilized in \ref{fig:cool} are $\beta_2 = 0.01$. A geometric cooling schedules is as defined in [[eq:cool]]. This
schedule type is most widely used in practice [cite:@keller-2019-multi-objec]. As such, it will also be employed by this
work.

#+name: eq:cool
  \begin{equation}
  t_m = \beta t_{m-1}
  \end{equation}

The gain variable, $\beta$, in \ref{fig:cool} evaluated at $\beta = 0.995$. The value of $\beta$ may vary anywhere between the range
$[0,1)$. The further $\beta$ is from 1, the quicker the function converges to zero. \ref{fig:geometric} demonstrates this
principle by plotting the geometric schedule using varying values of $\beta$.

#+begin_src latex
  \begin{figure}[t!]
    \begin{subfigure}[t]{0.5\textwidth}
      \centering \includegraphics[width=\textwidth]{img/cool_func.png}
      \caption{Geometric, linear, and exponential cooling schedules.}
      \label{fig:cool}
    \end{subfigure}
    ~
    \begin{subfigure}[t]{0.5\textwidth}
      \centering \includegraphics[width=\textwidth]{img/geometric.png}
      \caption{Geometric cooling schedule utilizing various value of $\beta$.}
      \label{fig:geometric}
    \end{subfigure}
  \end{figure}
#+end_src

*** Acceptance Criteria
:PROPERTIES:
:CUSTOM_ID: sec:acceptance
:END:

#+include: ../sup-doc/sa-pap-paper/sections/simulated-annealing.org::#sec:sa-acceptance :only-contents t

*** Neighbor Generators and Wrappers
:PROPERTIES:
:CUSTOM_ID: sec:generation-mechanisms
:END:

#+include: ../sup-doc/sa-pap-paper/sections/simulated-annealing.org::#sec:sa-generation-mechanisms :only-contents t

*** Alternative Heuristic Implementation
:PROPERTIES:
:CUSTOM_ID: sec:heuristic-implementation
:END:

#+include: ../sup-doc/sa-pap-paper/sections/simulated-annealing.org::#sec:sa-heuristic-implementation :only-contents t

** Optimization Algorithm
:PROPERTIES:
:CUSTOM_ID: sec:optimization-algorithm
:END:

#+include: ../sup-doc/sa-pap-paper/sections/optimization-algorithm.org::#sec:sa-optimization-algorithm :only-contents t

** Example
:PROPERTIES:
:CUSTOM_ID: sec:sa-pap-example
:END:

#+include: ../sup-doc/sa-pap-paper/sections/example.org::#sec:sa-example :only-contents t
